mode: "local" #local, dev, prod

data_source_name: "user=your_db_user password=your_db_password dbname=your_db_name host=localhost port=5432 sslmode=disable" # for postgre

external_api_url: "/your_external_api_url"

migrations_paths:
  up: "your_path_to_up_migrations_dir"
  down: "your_path_to_down_migrations_dir"

http_server:
  address: "localhost:8082"
  read_timeout: 4s
  write_timeout: 4s
  idle_timeout: 60s
